<template>
  <div class="a-card p-16">
    <div class="content_group">
      <h2 class="h2-text">Work experiences</h2>
      <LazyExperienceGroup :items="experiences" />
    </div>
  </div>
</template>

<script>
export default {
  name: 'WorkExperiences',
  data() {
    return {
      experiences: [
        {
          id: 1,
          logo: require('~/assets/img/company/agit.jpg'),
          company: 'Astra Graphia Information Technology',
          type: 'Full Time',
          occupation: 'Senior UX Designer',
          start_date: 'April 2021',
          end_date: 'Now',
          website: '',
          task_1: 'Always meet task success above 80%',
          task_2: 'Collaboration with stakeholders to define business flow',
          task_3: 'UX Workshop',
          task_4: 'Collaboration with UX teammates to define user journey map, user flow, and information architecture',
          task_5: 'Wireframing, designing, and prototyping website app, mobile app and tablet app',
          task_6: 'Do usability testing using maze and useberry app',
          task_7: 'Create design system for website app, mobile app and tablet app',
          task_8: 'Create documentation for all design process',
          task_9: 'Collaboration with front end dev to define components, templates, and layout',
          task_10: 'Craete visual data using google data studio app',
          task_11: '',
          task_12: '',
          task_13: '',
          task_14: '',
        },
        {
          id: 2,
          logo: require('~/assets/img/company/finpedia.png'),
          company: 'Finpedia.id',
          type: 'Freelance',
          occupation: 'UX Designer',
          start_date: 'January 2021',
          end_date: 'March 2021',
          website: '',
          task_1: 'Collaboration with stakeholders to define business flow',
          task_2: 'UX Workshop',
          task_3: 'Define user persona, user journey map, user flow, and information architecture',
          task_4: 'Wireframing, designing, and prototyping website app and mobile app',
          task_5: 'Create design system for website app and mobile app',
          task_6: 'Implement components, templates, and layout into front end using Vue JS & Nuxt JS',
          task_7: 'Track performance using google analytics',
          task_8: 'A/B Testing using google optimize',
          task_9: 'Craete visual data using google data studio app',
          task_10: '',
          task_11: '',
          task_12: '',
          task_13: '',
          task_14: '',
        },
        {
          id: 3,
          logo: require('~/assets/img/company/compas.jpg'),
          company: 'Compas.co.id',
          type: 'Full Time',
          occupation: 'UX Designer and Front End Developer',
          start_date: 'September 2020',
          end_date: 'February 2021',
          website: '',
          task_1: 'Collaboration with stakeholders to define business flow',
          task_2: 'Collaboration with UX Researcher to do user research',
          task_3: 'UX Workshop',
          task_4: 'Collaboration with UX teammates to define user persona, affinity map, user journey map, user flow, and information architecture',
          task_5: 'Wireframing, designing, and prototyping website app and mobile app',
          task_6: 'Do usability testing using maze app',
          task_7: 'Create design system for website app and mobile app',
          task_8: 'Create documentation for all design process',
          task_9: 'Implement components, templates, and layout into front end using Vue JS & Nuxt JS',
          task_10: 'Track performance using google analytics',
          task_11: 'A/B Testing using google optimize',
          task_12: 'Craete visual data using google data studio app',
          task_13: '',
          task_14: '',
        },
        {
          id: 4,
          logo: require('~/assets/img/company/telunjuk.jpeg'),
          company: 'Telunjuk.com',
          type: 'Full Time',
          occupation: 'UX Designer and Front End Developer',
          start_date: 'April 2018',
          end_date: 'February 2021',
          website: '',
          task_1: 'Analyze and increase organic search around 80%',
          task_2: 'Analyze and increase conversion rate around 50%',
          task_3: 'Collaboration with stakeholders to define business flow',
          task_4: 'Collaboration with UX Researcher to do user research',
          task_5: 'UX Workshop',
          task_6: 'Collaboration with UX teammates to define user persona, affinity map, user journey map, user flow, and information architecture',
          task_7: 'Wireframing, designing, and prototyping website app and mobile app',
          task_8: 'Do usability testing using maze app',
          task_9: 'Create design system for website app and mobile app',
          task_10: 'Create documentation for all design process',
          task_11: 'Implement components, templates, and layout into front end using Vue JS & Nuxt JS',
          task_12: 'Track performance using google analytics',
          task_13: 'A/B Testing using google optimize',
          task_14: 'Craete visual data using google data studio app',
        },
      ],
    }
  },
}
</script>
